version: '3.8'
services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./apps:/app
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
