---
- name: Update etc/hostname
  hosts: apps
  become: true

  tasks:
    - name: Update /etc/hostname with new hostname
      lineinfile:
        path: /etc/hostname
        regexp: 'ip-10-1-1-9'
        line: "server-apps"
      when: "'apps' in group_names"