---
- name: Update etc/hosts
  hosts: apps
  become: true

  tasks:
    - name: Update /etc/hosts with new hostname
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: "127.0.1.1 devops-apps"
      when: "'apps' in group_names"